channels:
  - conda-forge
dependencies:
  - numpy
  - pip
  - python
  - matplotlib
  - jax
  - astropy
  - scipy
  - arviz
  - corner
  - pip:
    - jaxoplanet
    - git+https://github.com/SamMerc/emcee-jax.git

